apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqrr-deployment
  labels:
    app: sqrr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqrr
  template:
    metadata:
      labels:
        app: sqrr
    spec:
      containers:
        - name: sq
          image: $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/sqrr:$SEM_VER
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["/app/superQueueRequestRouter"]
          args:
            - -etcd-hosts=etcd.default.svc.cluster.local:2379
          resources:
            requests:
              memory: '1024M'
              cpu: '1'
            limits:
              memory: '2048M'
              cpu: "1"
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sqrr-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: sqrr
